tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/config/routes.rb
Naturalskeptics::Application.routes.draw do

  get "pages/home"

  get "pages/contact"

  get "jscalc/index"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders
  resources :line_items
  resources :carts
  resources :commodities
  resources :home
  resources :xmlusers
  resources :comments
  resources :discussions
  resources :users

  resources :discussions do
    resources :comments
  end

  get "home/index"
  get "home/mygems"
  get "xmlusers/index"
  get "jscalc/index"

  match '/mygems' => "home#mygems", :as => "mygems"
  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/carts/remove/:id' => 'line_items#destroy'

  root :to => 'home#index'

end

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/models/discussion.rb
# == Schema Information
#
# Table name: discussions
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  introduction       :text
#  description        :text
#  user_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  caption            :string(255)
#

class Discussion < ActiveRecord::Base
  attr_accessible :description, :introduction, :title, :user_id, :photo,:caption

    has_attached_file :photo,
                      :styles => {:medium => "300x300>", :thumb => "100x100"},
                      :default_url => "/images/:style/missing.png"

  belongs_to :user
  has_many :comments

  validates :title,
            :description,
            :presence => true

  def uname
    user.email.split('@').first
  end

  def self.search search_query

    if search_query
      find :all, conditions: ["title LIKE ? OR description LIKE ?",
                              "%#{search_query}%", "%#{search_query}%"]
    else
      find :all
    end
  end
end

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  def index
    @cart = current_cart
    #@discussions = Discussion.all

    @discussions = Discussion.paginate(per_page: 5,
                                       page: params[:page],
                                       order: "title ASC").search(params[:search_query])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discussions }
    end
  end

  def show
    @cart = current_cart
    @discussion = Discussion.find(params[:id])

    @thomas = @discussion.comments.paginate(:per_page => 5,
                                            :page => params[:page],
                                            :order => "created_at DESC").search(params[:search_query])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discussion }
    end
  end

  def new
    @discussion = Discussion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discussion }
    end
  end

  def edit
    @discussion = Discussion.find(params[:id])
  end

  def create
    @discussion = Discussion.create(params[:discussion])

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render json: @discussion, status: :created, location: @discussion }
      else
        format.html { render action: "new" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      if @discussion.update_attributes(params[:discussion])
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy

    respond_to do |format|
      format.html { redirect_to discussions_url }
      format.json { head :no_content }
    end
  end
end

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/helpers/discussions_helper.rb
module DiscussionsHelper
end

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/views/discussions/_form.html.erb
<%= form_for @discussion,  :html => { :multipart => true } do |f| %>

  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@discussion.errors.count, "error") %>
        prohibited this discussion from being saved:
      </h2>

      <ul>
       <% @discussion.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
   </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>

  <div class="field">
    <%= f.file_field :photo %>
   </div>

  <div class="actions">
    <%= f.submit  class: "button success"%>
  </div>
<% end %>

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/views/discussions/_search_and_paginate.html.erb
<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @discussions %>
  </div>  <br/>
  <%= will_paginate @discussions %>
</div> <br/>

<div id="searchbutton" class="controls">

  <%= form_tag discussions_path, :method => 'get' do %>

      <p>
        <%= text_field_tag :search_query, params[:search_query] %>  &nbsp;
        <%= submit_tag "Search", :name => nil, class: "button" %>

        <br/>
        <br/>
      </p>
  <% end %>
</div>

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/views/discussions/_will_paginate.html.erb
<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @thomas %>
  </div> <br />

  <%= will_paginate  @thomas %>

</div>  <br />

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/views/discussions/index.html.erb
<h1>Listing discussions</h1>

<table>
  <% @discussions.each do |discussion| %>
      <tr>
        <td>
          <figure>
            <%= link_to (image_tag discussion.photo.url(:thumb)), discussion %>

          </figure>
        </td>
        <td><%= discussion.title %></td>
        <td><%= discussion.introduction %></td>
        <td><%= link_to 'Show', discussion, class: 'button secondary tiny' %></td>

        <% if current_user and current_user.admin %>
        <td><%= link_to 'Edit', edit_discussion_path(discussion), class: 'button success tiny' %></td>
        <td><%= link_to 'Destroy', discussion, method: :delete, data: {confirm: 'Are you sure?'}, class: 'button alert tiny' %></td>
         <% end %>

      </tr>
  <% end %>
</table><br/>

<%= render partial: 'discussions/search_and_paginate' %>

<% if current_user and current_user.admin %>
 <%= link_to 'New Discussion', new_discussion_path, class: "button success" %>
 <% end %>

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

tomd_waf_submitted/submitted_jan2014/tomdowling_x12113441_waf_project/naturalskeptics/app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @discussion.title %> </h1>

<figure>
 <%= image_tag @discussion.photo.url(:medium) %>
  <figcaption><%= @discussion.caption %></figcaption>
</figure>

<h2>Introduction</h2>
<p><%= @discussion.introduction %></p>

<h3>  Description</h3>

   <div><%= @discussion.description %></div>
<% if current_user.present? %>
    <br/><h4>Please Leave Your Comments</h4><br/>
<% else %>
    <br/> <h4>You must Log-in to Leave a Comment</h4><br/>

    <% end %>
<table>
  <thead>
  <tr>
    <th>Comment</th>
    <th>User Name</th>
    <th>Time</th>
    <th> </th>
    <th> </th>
  </tr>
  </thead>
  <tbody>

  <%  @thomas.each do |comment| %>
      <tr>

        <td><%= sanitize comment.text %></td>

        <td> <%= comment.uname%>        </td>

        <td><%= time_ago_in_words(comment.created_at) + " ago" %></td>

        <% if current_user and current_user.admin %>

            <td><%= link_to 'Edit Comment', edit_comment_path(comment.id),class: 'button success tiny' %></td>
            <td><%= link_to 'Destroy', comment, method: :delete,
                            data: {confirm: 'Are you sure?'}, class: 'button alert tiny' %></td>

            <% else %>

            <% if current_user.present? %>
                                                  .
        <% if comment.user_id.to_s.include?(current_user.id.to_s) %>

            <td><%= link_to 'Edit Comment', edit_comment_path(comment.id),class: 'button success tiny' %></td>
            <td><%= link_to 'Destroy', comment, method: :delete,
                                    data: {confirm: 'Are you sure?'}, class: 'button alert tiny' %></td>
           <% end %>
         <% end %>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<%= render partial: 'discussions/will_paginate' %>

<% if current_user.present? %>

<%= form_for([@discussion, @discussion.comments.build]) do |f| %>
    <div class="field">
      <%= f.hidden_field :user_id %>
      <%= f.hidden_field :discussion_id %>
    </div>
    <div class="field">
      <%= f.label :text, "Add your comment here" %>
      <br/>
      <%= f.text_area :text, size: "300x10" %>
    </div>
    <div class="actions"><br/>
      <%= f.submit "Add Your Comment", class: "button" %>
    </div>
<% end %>

    <% end %>

<% if current_user and current_user.admin  %>
    <div> <%= link_to 'Comments Page', comments_path,
                     class: "button secondary tiny" %></div>
<% end  %>