email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/config/routes.rb
Naturalskeptics::Application.routes.draw do

  get "pages/home"

  get "pages/contact"

  get "jscalc/index"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders
  resources :line_items
  resources :carts
  resources :commodities
  resources :home
  resources :xmlusers
  resources :comments
  resources :discussions
  resources :users

  resources :discussions do
    resources :comments
  end

  get "home/index"
  get "home/mygems"
  get "xmlusers/index"
  get "jscalc/index"

  match '/mygems' => "home#mygems", :as => "mygems"
  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/carts/remove/:id' => 'line_items#destroy'

  root :to => 'home#index'

end

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, :dependent => :destroy

  def add_commodity(commodity)
    current_item = line_items.where(:commodity_id => commodity.id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = LineItem.new(:commodity_id => commodity.id)
      line_items << current_item
    end
    current_item
  end

  def total_price
    total = 0

    line_items.each do |line_item|
      #total += line_item.commodity.price * line_item.quantity
      total += line_item.sales_price.to_f * line_item.quantity

    end
    total
  end
end

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @carts = Cart.all
    @cart = current_cart

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  def your_cart
    redirect_to :action => "show", :id => current_cart.id
  end

  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to commodities_url,
                                notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/helpers/carts_helper.rb
module CartsHelper
end

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/views/carts/_cart.html.erb
<h2 class="cartheader">Your Cart</h2>
<% if user_signed_in? %>
 <h4 class="cartheader">
   <%= username %>
 </h4>
<% end %>
<table id="cartTable">
  <td></td>
  <td></td>
  <td>Unit Price</td>
  <%= render(cart.line_items) %>

  <tr>
    <td>Total Price</td>
    <td></td>
    <td></td>
    <td> <%= number_to_currency(cart.total_price,
                                :unit => '&euro;',
                                precision: 0) %>
    </td>
  </tr>
</table>

<%= button_to 'Empty cart', @cart,
              :method => :delete,
              :id => "emptyCartButton",
              :confirm => 'Are you sure?',
              :class => "button secondary tiny" %>

<div class="checkOutButtons">
  <%= button_to "Checkout", new_order_path,
                method: :get,
                :id => "checkOutButton",
                :class => "button secondary tiny", remote: true %>
</div>

<div class="checkOutButtons">
  <%= button_to "Smaller", new_home_path,
                method: :get,
                :id => "smallerCartButton",
                :class => "button secondary tiny", remote: true %>
</div>

<div id="cartDragMessage"> I am draggable</div>
<br />

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/views/carts/_cartSmall.html.erb
<h4 class="cartheader">Your Cart</h4>
<h6 class="cartheader"><%= username %></h6>
<div>
<table>
  <tr>
    <td>Total Price</td>
    <td></td>
    <td></td>
    <td> <%= number_to_currency(@cart.total_price,
                                :unit => '&euro;',
                                precision: 0) %>
    </td>
  </tr>
</table>
</div>
<div class="checkOutButtons">
  <%= link_to "Larger", commodities_path,
              id: "largerCartButton",
              class: "button right  tiny secondary" %>

  <%= button_to "Checkout", new_order_path,
                method: :get,
                :id => "checkOutButton",
                :class => "button secondary tiny",
                remote: true %>
</div>

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

email_version_Jan_25/tomDowling_x12113441_waf_final/naturalskeptics/app/views/carts/show.html.erb
<p id = "notice"><%= notice %></p>
<h2>Your Cart from show</h2>

<table>
  <%= render(@cart.line_items) %>
  <%= render(@cart) %>
  <br />
  <tdTotal Price: <%= number_to_currency(@cart.total_price, :unit => '&euro;') %><br /></td>
</table>

 <p> <%= button_to 'Empty cart', @cart, :method => :delete,
                                        :confirm => 'Are you sure?',
                                        :class => "button success small 5 radius "%></p>
<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>