naturalskeptics/config/routes.rb
Naturalskeptics::Application.routes.draw do

  get "pages/home"
  get "pages/contact"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :orders
  resources :line_items
  resources :carts
  resources :commodities
  resources :home
  resources :xmlusers
  resources :comments
  resources :discussions
  resources :users
  resources :products

  resources :discussions do
    resources :comments
  end

  get "home/index"
  get "home/mygems"
  get "xmlusers/index"
  get "jscalc/index"

  match '/mygems' => "home#mygems", :as => "mygems"
  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/carts/remove/:id' => 'line_items#destroy'
  match '/indexnew' => "commodities#indexnew", :as =>  "indexnew"
  match '/indextwo' => "users#indextwo", :as =>  "indextwo"

  root :to => 'home#index'

end

naturalskeptics/app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to "Home", root_path %>
      </h1>
    </li>
  </ul>
  <section class="top-bar-section"> <!-- Right Nav Section -->
    <ul class="right">
      <li class="active">
      <%= link_to "Calculator", "jscalc/index", remote: false %>
      </li>
      <li class="has-dropdown">

        <%= link_to "RubyGems/Git",
                    "https://rubygems.org/gems/jscalc" %>

        <ul class="dropdown">
          <li><%= link_to "jscalc/RubyGems",
                          "https://rubygems.org/gems/jscalc"%></li>
          <li><%= link_to "binToDec/RubyGems",
                          "https://rubygems.org/gems/binToDec"%></li>
          <li><%= link_to "priceMarkUp/RubyGems",
                          "https://rubygems.org/gems/priceMarkup"%></li>
          <li><%= link_to "skeptics/GitHub",
                          "https://github.com/tomGdow/skeptics"%></li>
          <li><%= link_to "tomGdow/GitHub",
                          "https://github.com/tomGdow"%></li>
          <li><%= link_to "jscalc/Heroku", "http://tgd-jscalc.herokuapp.com/" %></li>
        </ul>
      </li>
    </ul>
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="has-dropdown active">
        <%= link_to "Commodities", commodities_path, remote: false %>
        <ul class="dropdown">

          <li><%= link_to "Index/Search", commodities_path, remote: false %></li>
          <li><%= link_to "Json/Search", "/indexnew"%></li>

        </ul>
      </li>

      <li>
        <%= link_to "Gems", mygems_path, :class => "ajaxClass" %>
      </li>

      <% if  current_user.present?%>

      <li>
        <%= link_to "Profile", user_path(current_user.id), remote: false %></li>

      <% end %>
      <li class="has-dropdown">
        <%= link_to "Discussions", discussions_path, remote: false %>
        <ul class="dropdown">

          <li><%= link_to "Index", discussions_path, remote: false %></li>
          <li><%= link_to "Popper", discussion_path(8), remote: false %></li>
          <li><%= link_to "Watson", discussion_path(10), remote: false %></li>
          <li><%= link_to "Sanger", discussion_path(11), remote: false %></li>
          <li><%= link_to "Crick", discussion_path(12), remote: false %></li>
          <li><%= link_to "Pauling", discussion_path(13), remote: false %></li>
          <li><%= link_to "Hodgkin", discussion_path(14), remote: false %></li>

        </ul>
      </li>

      <% if current_user and current_user.admin %>
          <li class="has-dropdown">
            <%= link_to "Users", xmlusers_path, remote: false %>
            <ul class="dropdown">
              <li><%= link_to "Index/Search", "/indextwo"%></li>
              <li><%= link_to "Json/Search", users_path %></li>
              <li><%= link_to "Dynamic XML", xmlusers_path, remote: false %></li>
              <li><%= link_to("XML file", "/xmlNewUsers.xml",
                            :target => '_blank') %> </li>
            </ul>
          </li>
          <li><%= link_to "Comments", comments_path, remote: true %></li>
      <% end %>
    </ul>
  </section>
</nav>

naturalskeptics/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="skepticsApp">

<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title><%= content_for?(:title) ? yield(:title) : "Natural Skeptics" %></title>
  <%= stylesheet_link_tag "jscalc.css" %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>

</head>
<body class='<%= controller.controller_name %>' ng-controller="SkepticsCtrl">
<%= render partial: 'layouts/nav' %>
<%= render partial: 'layouts/breadcrumbs' %>
<%= render partial: 'layouts/hiddenDivs' %>

<div class="row ">
  <div class=" large-3 column">
  </div>
  <div class="large-9 column" id = "yieldId">
    <%= yield %>
  </div>
</div>

<%= javascript_include_tag "application" %>

</body>
</html>